# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d511a3d110cd902b684cf69497469824d8213479f568788fe1dff1d39a2d995c0628a172d52bc079e7034a187d5ad0428cc3aeea7f12790d7034182aa3b6b4a

test:
  secret_key_base: c8db12f109201f88a580ca19a1e36120523f710e01c554b1d36dc4df7b9407be621ce31e47dd7c188a160f8d10f9de6eb517dc84d390229ff306e0e755ce6482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
